# Generated by Django 5.2.7 on 2025-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_accessible',
            field=models.BooleanField(default=False, verbose_name='Доступен без авторизации'),
        ),
    ]
